### ISSUE TITLE
Finalization bug

### ISSUE THREAD

**Issue by brothermechanic** [animate1978/MB-Lab#302] opened 2020-09-17 16:05 UTC
**Logs**
```
Python: Traceback (most recent call last):
  File "/usr/share/blender/scripts/addons/MB-Lab-9999/__init__.py", line 1703, in execute
    mblab_humanoid.set_rest_pose()
  File "/usr/share/blender/scripts/addons/MB-Lab-9999/humanoid.py", line 1266, in set_rest_pose
    self.sk_engine.apply_armature_modifier()
  File "/usr/share/blender/scripts/addons/MB-Lab-9999/skeletonengine.py", line 119, in apply_armature_modifier
    algorithms.apply_modifier(obj, armature_modifier)
  File "/usr/share/blender/scripts/addons/MB-Lab-9999/algorithms.py", line 1069, in apply_modifier
    bpy.ops.object.modifier_apply(apply_as='DATA', modifier=modifier_name)
  File "/usr/share/blender/2.91/scripts/modules/bpy/ops.py", line 202, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized

location: <unknown location>:-1
```
**Screenshots**
![Screenshot_20200917_190340](https://user-images.githubusercontent.com/3109995/93496932-5c78f000-f8ff-11ea-9242-81112ead01b1.jpg)

**Additional context**
Hello
Im' new there
1) I want to pose generated human
2) I push Finalise button and get a bug

**Comment by Bolche** [comment] 2020-09-20 20:17
Looks like a duplicate of bug #297 
Check the thread for answers

**Comment by animate1978** [comment] 2020-12-22 05:25
The recent pull requests to 'master' should resolve this issue

**Closed by animate1978** 2020-12-22 05:25 UTC
