### ISSUE TITLE
Can't Finaliziation !

### ISSUE THREAD

**Issue by Qomolangma888** [animate1978/MB-Lab#297] opened 2020-08-03 03:22 UTC
I use Blender 2.90 Beta everyday built version, I test the lastest MB-Lab, when I click Finaliziation Button, Blender shows warning information " can not keyword : apply_as ", so I report the bug, meanwhile I thanks a lot of your hard work!

**Comment by stotka1** [comment] 2020-08-15 06:28
I have the same problem more or less. Using 2.90.0 Beta
![blender_dKn1QWQY6n](https://user-images.githubusercontent.com/4647470/90306821-717af180-df03-11ea-8681-bf74690d9580.png)

**Comment by ldo** [comment] 2020-08-15 08:05
Don’t take screenshots of text, copy and paste the text itself. Makes it easier to search and copy/paste.

**Comment by Qomolangma888** [comment] 2020-08-18 01:30
I test MB-Lab on Blender 2.83.4 LTS, it can run normally, so I think that there are some changes in Blender 2.90 Beta.

**Comment by OBI-Ron** [comment] 2020-09-04 15:00
Same here with official Blender 2.9 on Linux - Ubuntu 18.04:

`Traceback (most recent call last):
  File "/home/MyHomeDir/.config/blender/2.90/scripts/addons/MB-Lab/__init__.py", line 1329, in execute
    mblab_humanoid.set_rest_pose()
  File "/home/MyHomeDir/.config/blender/2.90/scripts/addons/MB-Lab/humanoid.py", line 1194, in set_rest_pose
    self.sk_engine.apply_armature_modifier()
  File "/home/MyHomeDir/.config/blender/2.90/scripts/addons/MB-Lab/skeletonengine.py", line 119, in apply_armature_modifier
    algorithms.apply_modifier(obj, armature_modifier)
  File "/home/MyHomeDir/.config/blender/2.90/scripts/addons/MB-Lab/algorithms.py", line 1142, in apply_modifier
    bpy.ops.object.modifier_apply(apply_as='DATA', modifier=modifier_name)
  File "/programs/Blender_2.9/2.90/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized

location: <unknown location>:-1`

**Comment by fedorenchik** [comment] 2020-09-06 07:02
Same on official Blender 2.90.0 from snap store on Ubuntu 20.04:

```
Traceback (most recent call last):
  File "/home/leonid/.config/blender/2.90/scripts/addons/MB-Lab/__init__.py", line 1703, in execute
    mblab_humanoid.set_rest_pose()
  File "/home/leonid/.config/blender/2.90/scripts/addons/MB-Lab/humanoid.py", line 1266, in set_rest_pose
    self.sk_engine.apply_armature_modifier()
  File "/home/leonid/.config/blender/2.90/scripts/addons/MB-Lab/skeletonengine.py", line 119, in apply_armature_modifier
    algorithms.apply_modifier(obj, armature_modifier)
  File "/home/leonid/.config/blender/2.90/scripts/addons/MB-Lab/algorithms.py", line 1069, in apply_modifier
    bpy.ops.object.modifier_apply(apply_as='DATA', modifier=modifier_name)
  File "/snap/blender/45/2.90/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized

location: <unknown location>:-1
```

**Comment by Knight-General** [comment] 2020-09-06 22:05
i am having the same issue on windows 10, blender 2.9 and MB-Lab 1.7.8

the other issue i am having is that i cannot copy and paste the text as when i move the mouse the message disappears. any sort of fix for this issue is greatly appreciated.

**Comment by calben** [comment] 2020-09-07 01:52
Operator was moved.
Should be a quick fix, will check to see if there are other issues.

**Comment by calben** [comment] 2020-09-07 02:14
Looks like that was the only issue.
A pull request has been opened to fix the problem. 
In the meantime there's a branch on my fork that fixes the issue: https://github.com/calben/MB-Lab/tree/fix-2.90-finalize

**Comment by pdesopo** [comment] 2020-09-07 21:57
@calben Thanks for providing the fix. I have tried to install your version but now I'm getting this error

`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'MB-Lab-fix-2'`

**Comment by calben** [comment] 2020-09-08 14:01
That's a new one.
Potentially a stupid exercise, but could you walk me through how you installed the version?
Have you made modifications to MB-Lab in the past?
The string `fix-2` does not occur in my copy of the repository.

**Comment by pdesopo** [comment] 2020-09-08 20:03
> That's a new one.
> Potentially a stupid exercise, but could you walk me through how you installed the version?
> Have you made modifications to MB-Lab in the past?
> The string `fix-2` does not occur in my copy of the repository.

Hey Calben,

I first uninstalled 1.7.8.  I then installed your fix version from Add-ons / Install and pointed to the zip file. The contents is indeed copied into the add-ons folder:
...\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab-fix-2.90-finalize
but then when I try to activate the add-on I get the warning I posted above and the add-ons remains inactive.

**Comment by calben** [comment] 2020-09-08 20:29
Try renaming the directory from `MB-Lab-fix-2.90-finalize` to `MB-Lab`.
If I remember correctly, Blender gets a little upset if the script name in the `bl_info` doesn't match the script's directory.

**Comment by pdesopo** [comment] 2020-09-08 22:03
> Try renaming the directory from `MB-Lab-fix-2.90-finalize` to `MB-Lab`.
> If I remember correctly, Blender gets a little upset if the script name in the `bl_info` doesn't match the script's directory.

Thanks a lot, Calben! 
That worked beautifully and so did the Finalize function.

**Comment by marvinweish** [comment] 2020-09-09 12:17
Hey Calben,

I am having issues with the finalization of my character, I have downloaded your fix and also changed the name of the folder in the zip file to MB_Lab and it bring this issue 

Traceback (most recent call last):
  File "C:\Users\marvo\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab\__init__.py", line 1708, in execute
    mblab_humanoid.update_displacement()
  File "C:\Users\marvo\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab\humanoid.py", line 508, in update_displacement
    self.mat_engine.calculate_displacement_texture(age_factor, tone_factor, mass_factor)
  File "C:\Users\marvo\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab\materialengine.py", line 311, in calculate_displacement_texture
    if images_scale(disp_data_image, disp_img):
  File "C:\Users\marvo\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab\materialengine.py", line 348, in images_scale
    image1.scale(*image2.size)
RuntimeError: Error: Image 'human_female_displacement.png' does not have any image data


location: <unknown location>:-1

What is it that I should do?

**Comment by calben** [comment] 2020-09-09 12:39
*Looks* like your data directory may have gotten bungled along the way.

1. Double check that `MB-Lab/data/textures/human_female_displacement.png` exists.
1. If it does exist, is this something you can reliably reproduce?
1. If yes, with what settings was the character generated? 

If it's a code problem, I'll look at it this evening after work.

**Comment by marvinweish** [comment] 2020-09-09 15:56
Thank you for
The file exists, I have checked with reference to the other versions of the add-on and it's the same file.
I just used the body measurements morph tool and use cycles engine. it is for the afro female  but the afro male finalizes just fine.
I am running the add-on ticking off the censor option.
The models are now finalizing after restarting blender and doing no morfs to the characters. But now all the female models have the censor even when the check box is checked while the male charcters are working properly.

**Comment by lauramegurine** [comment] 2020-09-11 02:25
Hi I have an error every time I try to finalize a model, I have the fix for 2.90... but I have no luck.
This is what I got, I even try with just a basic model without touching anything. Still have the error.
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab\__init__.py", line 1703, in execute
    mblab_humanoid.set_rest_pose()
  File "C:\Users\Usuario\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab\humanoid.py", line 1266, in set_rest_pose
    self.sk_engine.apply_armature_modifier()
  File "C:\Users\Usuario\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab\skeletonengine.py", line 119, in apply_armature_modifier
    algorithms.apply_modifier(obj, armature_modifier)
  File "C:\Users\Usuario\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab\algorithms.py", line 1069, in apply_modifier
    bpy.ops.object.modifier_apply_as_shapekey(modifier=modifier_name)
  File "D:\Aplicaciones\Blender Foundation\Blender 2.90\2.90\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized

location: <unknown location>:-1

**Comment by calben** [comment] 2020-09-11 22:29
Yup still some issues for sure.  Should be able to address it some this weekend.

**Comment by FinnFrotscher** [comment] 2020-11-10 23:21
Will there be a 2.7.9 release soon? i am running into this issue on caucasian and afro women

**Comment by animate1978** [comment] 2020-12-22 05:26
The recent pull requests to 'master' should resolve this issue

**Closed by animate1978** 2020-12-22 05:26 UTC

**Comment by FyaBoy** [comment] 2022-06-05 03:58
For anyone reading this, try converting it to mesh then finalizing it, fixed it for me
